{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import zipfile\n",
    "import plotly.express as px\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import requests\n",
    "from io import BytesIO\n",
    "import streamlit as st\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-04-08 14:35:59.688 No runtime found, using MemoryCacheStorageManager\n",
      "2025-04-08 14:35:59.718 No runtime found, using MemoryCacheStorageManager\n",
      "2025-04-08 14:35:59.757 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:35:59.760 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:35:59.763 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:00.270 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:00.272 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:07.389 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:07.392 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.133 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.134 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.136 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.138 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.139 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.143 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.145 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.151 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.152 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.155 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.161 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.162 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.163 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.164 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.166 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.167 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.168 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.171 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.175 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.181 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.182 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.184 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.185 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.189 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.198 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.236 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.240 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.241 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.244 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:08.245 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "/var/folders/s5/w23ysbrd4mb00w78_80t58tm0000gn/T/ipykernel_22462/4263245664.py:54: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.\n",
      "  plt.legend()\n",
      "2025-04-08 14:36:08.854 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:10.219 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:10.221 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:10.224 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:10.228 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:10.229 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:10.230 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:10.749 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:11.272 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:11.273 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:11.525 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:11.783 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-08 14:36:11.784 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "\n",
    "\n",
    "@st.cache_data\n",
    "def load_name_data():\n",
    "    names_file = 'https://www.ssa.gov/oact/babynames/names.zip'\n",
    "    response = requests.get(names_file)\n",
    "    with zipfile.ZipFile(BytesIO(response.content)) as z:\n",
    "        dfs = []\n",
    "        files = [file for file in z.namelist() if file.endswith('.txt')]\n",
    "        for file in files:\n",
    "            with z.open(file) as f:\n",
    "                df = pd.read_csv(f, header=None)\n",
    "                df.columns = ['name','sex','count']\n",
    "                df['year'] = int(file[3:7])\n",
    "                dfs.append(df)\n",
    "        data = pd.concat(dfs, ignore_index=True)\n",
    "    data['pct'] = data['count'] / data.groupby(['year', 'sex'])['count'].transform('sum')\n",
    "    return data\n",
    "\n",
    "df = load_name_data()\n",
    "\n",
    "\n",
    "\n",
    "df['total_births'] = df.groupby(['year', 'sex'])['count'].transform('sum')\n",
    "df['prop'] = df['count'] / df['total_births']\n",
    "st.title('My Name App')\n",
    "\n",
    "tab1, tab2, tab3 = st.tabs(['Overall', 'By Name', 'By Year'])\n",
    "\n",
    "with tab1: \n",
    "    st.write('Here is stuff about all the data')\n",
    "\n",
    "with tab2: \n",
    "    st.write('Name')\n",
    "\n",
    "    # pick a name\n",
    "    noi = st.text_input('Enter a name')\n",
    "    plot_female = st.checkbox('Plot female line')\n",
    "    plot_male = st.checkbox('Plot male line')\n",
    "    name_df = df[df['name']==noi]\n",
    "\n",
    "    fig = plt.figure(figsize=(15, 8))\n",
    "\n",
    "    if plot_female:\n",
    "        sns.lineplot(data=name_df[name_df['sex'] == 'F'], x='year', y='prop', label='Female')\n",
    "\n",
    "    if plot_male:\n",
    "        sns.lineplot(data=name_df[name_df['sex'] == 'M'], x='year', y='prop', label='Male')\n",
    "\n",
    "    plt.title(f'Popularity of {noi} over time')\n",
    "    plt.xlim(1880, 2025)\n",
    "    plt.xlabel('Year')\n",
    "    plt.ylabel('Proportion')\n",
    "    plt.xticks(rotation=90)\n",
    "    plt.legend()\n",
    "    plt.tight_layout()\n",
    "\n",
    "    st.pyplot(fig)\n",
    "\n",
    "\n",
    "\n",
    "with tab3:\n",
    "    st.write('Year')\n",
    "\n",
    "    year_of_interest = 1990 #int(st.text_input('Enter a year'))\n",
    "    #year_of_interest = int(year_of_interest)\n",
    "\n",
    "    #st.write(year_of_interest)\n",
    "\n",
    "    top_names = df[df['year'] == year_of_interest]\n",
    "\n",
    "   # st.write(top_names.shape)\n",
    "\n",
    "    top_female = top_names[top_names['sex'] == 'F'].nlargest(10, 'count')\n",
    "\n",
    "    f_year_fig= plt.figure(figsize=(15, 8))\n",
    "\n",
    "    plt.figure(figsize=(10,5))\n",
    "    sns.barplot(data=top_female, x='count', y='name')\n",
    "    plt.title(f\"Top 10 Female Names in {year_of_interest}\")\n",
    "    plt.xlabel('Count')\n",
    "    plt.ylabel('Name')\n",
    "    plt.tight_layout()\n",
    "\n",
    "\n",
    "    st.pyplot(f_year_fig)\n",
    "\n",
    "\n",
    "    m_year_fig = plt.figure(figsize=(10,5))\n",
    "    top_male = top_names[top_names['sex'] == 'M'].nlargest(10, 'count')\n",
    "\n",
    "    plt.figure(figsize=(10,5))\n",
    "    sns.barplot(data=top_male, x='count', y='name')\n",
    "    plt.title(f\"Top 10 Male Names in {year_of_interest}\")\n",
    "    plt.xlabel('Count')\n",
    "    plt.ylabel('Name')\n",
    "    plt.tight_layout()\n",
    "\n",
    "\n",
    "    st.pyplot(m_year_fig)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (727450548.py, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  Cell \u001b[0;32mIn[4], line 1\u001b[0;36m\u001b[0m\n\u001b[0;31m    streamlit run /Users/jasonwells/opt/anaconda3/envs/env386/lib/python3.12/site-packages/ipykernel_launcher.py\u001b[0m\n\u001b[0m              ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "#In terminal: streamlit run /Users/jasonwells/opt/anaconda3/envs/env386/lib/python3.12/site-packages/ipykernel_launcher.py "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "env386",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
